// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetUsersStatsOKCode is the HTTP code returned for type GetUsersStatsOK
const GetUsersStatsOKCode int = 200

/*GetUsersStatsOK stats

swagger:response getUsersStatsOK
*/
type GetUsersStatsOK struct {

	/*
	  In: Body
	*/
	Payload *GetUsersStatsOKBody `json:"body,omitempty"`
}

// NewGetUsersStatsOK creates GetUsersStatsOK with default headers values
func NewGetUsersStatsOK() *GetUsersStatsOK {

	return &GetUsersStatsOK{}
}

// WithPayload adds the payload to the get users stats o k response
func (o *GetUsersStatsOK) WithPayload(payload *GetUsersStatsOKBody) *GetUsersStatsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get users stats o k response
func (o *GetUsersStatsOK) SetPayload(payload *GetUsersStatsOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUsersStatsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetUsersStatsInternalServerErrorCode is the HTTP code returned for type GetUsersStatsInternalServerError
const GetUsersStatsInternalServerErrorCode int = 500

/*GetUsersStatsInternalServerError Server error

swagger:response getUsersStatsInternalServerError
*/
type GetUsersStatsInternalServerError struct {
}

// NewGetUsersStatsInternalServerError creates GetUsersStatsInternalServerError with default headers values
func NewGetUsersStatsInternalServerError() *GetUsersStatsInternalServerError {

	return &GetUsersStatsInternalServerError{}
}

// WriteResponse to the client
func (o *GetUsersStatsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
