// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetUsersBarcodeBarcodeParams creates a new GetUsersBarcodeBarcodeParams object
// no default values defined in spec.
func NewGetUsersBarcodeBarcodeParams() GetUsersBarcodeBarcodeParams {

	return GetUsersBarcodeBarcodeParams{}
}

// GetUsersBarcodeBarcodeParams contains all the bound params for the get users barcode barcode operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetUsersBarcodeBarcode
type GetUsersBarcodeBarcodeParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*barcode associated with user
	  Required: true
	  In: path
	*/
	Barcode int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetUsersBarcodeBarcodeParams() beforehand.
func (o *GetUsersBarcodeBarcodeParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rBarcode, rhkBarcode, _ := route.Params.GetOK("barcode")
	if err := o.bindBarcode(rBarcode, rhkBarcode, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindBarcode binds and validates parameter Barcode from path.
func (o *GetUsersBarcodeBarcodeParams) bindBarcode(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("barcode", "path", "int64", raw)
	}
	o.Barcode = value

	return nil
}
