// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/cccfr/gomete/models"
)

// PatchUsersIDOKCode is the HTTP code returned for type PatchUsersIDOK
const PatchUsersIDOKCode int = 200

/*PatchUsersIDOK edited user

swagger:response patchUsersIdOK
*/
type PatchUsersIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.User `json:"body,omitempty"`
}

// NewPatchUsersIDOK creates PatchUsersIDOK with default headers values
func NewPatchUsersIDOK() *PatchUsersIDOK {

	return &PatchUsersIDOK{}
}

// WithPayload adds the payload to the patch users Id o k response
func (o *PatchUsersIDOK) WithPayload(payload *models.User) *PatchUsersIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch users Id o k response
func (o *PatchUsersIDOK) SetPayload(payload *models.User) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchUsersIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PatchUsersIDBadRequestCode is the HTTP code returned for type PatchUsersIDBadRequest
const PatchUsersIDBadRequestCode int = 400

/*PatchUsersIDBadRequest Invalid input

swagger:response patchUsersIdBadRequest
*/
type PatchUsersIDBadRequest struct {
}

// NewPatchUsersIDBadRequest creates PatchUsersIDBadRequest with default headers values
func NewPatchUsersIDBadRequest() *PatchUsersIDBadRequest {

	return &PatchUsersIDBadRequest{}
}

// WriteResponse to the client
func (o *PatchUsersIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// PatchUsersIDNotFoundCode is the HTTP code returned for type PatchUsersIDNotFound
const PatchUsersIDNotFoundCode int = 404

/*PatchUsersIDNotFound id not existent

swagger:response patchUsersIdNotFound
*/
type PatchUsersIDNotFound struct {
}

// NewPatchUsersIDNotFound creates PatchUsersIDNotFound with default headers values
func NewPatchUsersIDNotFound() *PatchUsersIDNotFound {

	return &PatchUsersIDNotFound{}
}

// WriteResponse to the client
func (o *PatchUsersIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// PatchUsersIDInternalServerErrorCode is the HTTP code returned for type PatchUsersIDInternalServerError
const PatchUsersIDInternalServerErrorCode int = 500

/*PatchUsersIDInternalServerError Server error

swagger:response patchUsersIdInternalServerError
*/
type PatchUsersIDInternalServerError struct {
}

// NewPatchUsersIDInternalServerError creates PatchUsersIDInternalServerError with default headers values
func NewPatchUsersIDInternalServerError() *PatchUsersIDInternalServerError {

	return &PatchUsersIDInternalServerError{}
}

// WriteResponse to the client
func (o *PatchUsersIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
