// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostUsersIDTransferNoContentCode is the HTTP code returned for type PostUsersIDTransferNoContent
const PostUsersIDTransferNoContentCode int = 204

/*PostUsersIDTransferNoContent transaction successful

swagger:response postUsersIdTransferNoContent
*/
type PostUsersIDTransferNoContent struct {
}

// NewPostUsersIDTransferNoContent creates PostUsersIDTransferNoContent with default headers values
func NewPostUsersIDTransferNoContent() *PostUsersIDTransferNoContent {

	return &PostUsersIDTransferNoContent{}
}

// WriteResponse to the client
func (o *PostUsersIDTransferNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// PostUsersIDTransferBadRequestCode is the HTTP code returned for type PostUsersIDTransferBadRequest
const PostUsersIDTransferBadRequestCode int = 400

/*PostUsersIDTransferBadRequest bad request

swagger:response postUsersIdTransferBadRequest
*/
type PostUsersIDTransferBadRequest struct {
}

// NewPostUsersIDTransferBadRequest creates PostUsersIDTransferBadRequest with default headers values
func NewPostUsersIDTransferBadRequest() *PostUsersIDTransferBadRequest {

	return &PostUsersIDTransferBadRequest{}
}

// WriteResponse to the client
func (o *PostUsersIDTransferBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// PostUsersIDTransferPaymentRequiredCode is the HTTP code returned for type PostUsersIDTransferPaymentRequired
const PostUsersIDTransferPaymentRequiredCode int = 402

/*PostUsersIDTransferPaymentRequired sending user has insufficient funds on his account

swagger:response postUsersIdTransferPaymentRequired
*/
type PostUsersIDTransferPaymentRequired struct {
}

// NewPostUsersIDTransferPaymentRequired creates PostUsersIDTransferPaymentRequired with default headers values
func NewPostUsersIDTransferPaymentRequired() *PostUsersIDTransferPaymentRequired {

	return &PostUsersIDTransferPaymentRequired{}
}

// WriteResponse to the client
func (o *PostUsersIDTransferPaymentRequired) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(402)
}

// PostUsersIDTransferNotFoundCode is the HTTP code returned for type PostUsersIDTransferNotFound
const PostUsersIDTransferNotFoundCode int = 404

/*PostUsersIDTransferNotFound sending user id not existent

swagger:response postUsersIdTransferNotFound
*/
type PostUsersIDTransferNotFound struct {
}

// NewPostUsersIDTransferNotFound creates PostUsersIDTransferNotFound with default headers values
func NewPostUsersIDTransferNotFound() *PostUsersIDTransferNotFound {

	return &PostUsersIDTransferNotFound{}
}

// WriteResponse to the client
func (o *PostUsersIDTransferNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// PostUsersIDTransferInternalServerErrorCode is the HTTP code returned for type PostUsersIDTransferInternalServerError
const PostUsersIDTransferInternalServerErrorCode int = 500

/*PostUsersIDTransferInternalServerError server error

swagger:response postUsersIdTransferInternalServerError
*/
type PostUsersIDTransferInternalServerError struct {
}

// NewPostUsersIDTransferInternalServerError creates PostUsersIDTransferInternalServerError with default headers values
func NewPostUsersIDTransferInternalServerError() *PostUsersIDTransferInternalServerError {

	return &PostUsersIDTransferInternalServerError{}
}

// WriteResponse to the client
func (o *PostUsersIDTransferInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
