// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostUsersIDSpendNoContentCode is the HTTP code returned for type PostUsersIDSpendNoContent
const PostUsersIDSpendNoContentCode int = 204

/*PostUsersIDSpendNoContent success

swagger:response postUsersIdSpendNoContent
*/
type PostUsersIDSpendNoContent struct {
}

// NewPostUsersIDSpendNoContent creates PostUsersIDSpendNoContent with default headers values
func NewPostUsersIDSpendNoContent() *PostUsersIDSpendNoContent {

	return &PostUsersIDSpendNoContent{}
}

// WriteResponse to the client
func (o *PostUsersIDSpendNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// PostUsersIDSpendBadRequestCode is the HTTP code returned for type PostUsersIDSpendBadRequest
const PostUsersIDSpendBadRequestCode int = 400

/*PostUsersIDSpendBadRequest invalid input

swagger:response postUsersIdSpendBadRequest
*/
type PostUsersIDSpendBadRequest struct {
}

// NewPostUsersIDSpendBadRequest creates PostUsersIDSpendBadRequest with default headers values
func NewPostUsersIDSpendBadRequest() *PostUsersIDSpendBadRequest {

	return &PostUsersIDSpendBadRequest{}
}

// WriteResponse to the client
func (o *PostUsersIDSpendBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// PostUsersIDSpendNotFoundCode is the HTTP code returned for type PostUsersIDSpendNotFound
const PostUsersIDSpendNotFoundCode int = 404

/*PostUsersIDSpendNotFound id not existent

swagger:response postUsersIdSpendNotFound
*/
type PostUsersIDSpendNotFound struct {
}

// NewPostUsersIDSpendNotFound creates PostUsersIDSpendNotFound with default headers values
func NewPostUsersIDSpendNotFound() *PostUsersIDSpendNotFound {

	return &PostUsersIDSpendNotFound{}
}

// WriteResponse to the client
func (o *PostUsersIDSpendNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// PostUsersIDSpendInternalServerErrorCode is the HTTP code returned for type PostUsersIDSpendInternalServerError
const PostUsersIDSpendInternalServerErrorCode int = 500

/*PostUsersIDSpendInternalServerError server error

swagger:response postUsersIdSpendInternalServerError
*/
type PostUsersIDSpendInternalServerError struct {
}

// NewPostUsersIDSpendInternalServerError creates PostUsersIDSpendInternalServerError with default headers values
func NewPostUsersIDSpendInternalServerError() *PostUsersIDSpendInternalServerError {

	return &PostUsersIDSpendInternalServerError{}
}

// WriteResponse to the client
func (o *PostUsersIDSpendInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
