// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewPostUsersIDBuyBarcodeParams creates a new PostUsersIDBuyBarcodeParams object
// no default values defined in spec.
func NewPostUsersIDBuyBarcodeParams() PostUsersIDBuyBarcodeParams {

	return PostUsersIDBuyBarcodeParams{}
}

// PostUsersIDBuyBarcodeParams contains all the bound params for the post users ID buy barcode operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostUsersIDBuyBarcode
type PostUsersIDBuyBarcodeParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: body
	*/
	Barcode int64
	/*
	  Required: true
	  In: path
	*/
	ID int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostUsersIDBuyBarcodeParams() beforehand.
func (o *PostUsersIDBuyBarcodeParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body int64
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("barcode", "body", ""))
			} else {
				res = append(res, errors.NewParseError("barcode", "body", "", err))
			}
		} else {
			// no validation required on inline body
			o.Barcode = body
		}
	} else {
		res = append(res, errors.Required("barcode", "body", ""))
	}
	rID, rhkID, _ := route.Params.GetOK("id")
	if err := o.bindID(rID, rhkID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindID binds and validates parameter ID from path.
func (o *PostUsersIDBuyBarcodeParams) bindID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("id", "path", "int64", raw)
	}
	o.ID = value

	return nil
}
