// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostUsersIDDepositHandlerFunc turns a function with the right signature into a post users ID deposit handler
type PostUsersIDDepositHandlerFunc func(PostUsersIDDepositParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostUsersIDDepositHandlerFunc) Handle(params PostUsersIDDepositParams) middleware.Responder {
	return fn(params)
}

// PostUsersIDDepositHandler interface for that can handle valid post users ID deposit params
type PostUsersIDDepositHandler interface {
	Handle(PostUsersIDDepositParams) middleware.Responder
}

// NewPostUsersIDDeposit creates a new http.Handler for the post users ID deposit operation
func NewPostUsersIDDeposit(ctx *middleware.Context, handler PostUsersIDDepositHandler) *PostUsersIDDeposit {
	return &PostUsersIDDeposit{Context: ctx, Handler: handler}
}

/*PostUsersIDDeposit swagger:route POST /users/{id}/deposit/ users postUsersIdDeposit

adds amount (in cents) to the balance of the user with id

*/
type PostUsersIDDeposit struct {
	Context *middleware.Context
	Handler PostUsersIDDepositHandler
}

func (o *PostUsersIDDeposit) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostUsersIDDepositParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
