// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostUsersIDSpendHandlerFunc turns a function with the right signature into a post users ID spend handler
type PostUsersIDSpendHandlerFunc func(PostUsersIDSpendParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostUsersIDSpendHandlerFunc) Handle(params PostUsersIDSpendParams) middleware.Responder {
	return fn(params)
}

// PostUsersIDSpendHandler interface for that can handle valid post users ID spend params
type PostUsersIDSpendHandler interface {
	Handle(PostUsersIDSpendParams) middleware.Responder
}

// NewPostUsersIDSpend creates a new http.Handler for the post users ID spend operation
func NewPostUsersIDSpend(ctx *middleware.Context, handler PostUsersIDSpendHandler) *PostUsersIDSpend {
	return &PostUsersIDSpend{Context: ctx, Handler: handler}
}

/*PostUsersIDSpend swagger:route POST /users/{id}/spend/ users postUsersIdSpend

subtracts amount (in cents) from the balance of the user with id

*/
type PostUsersIDSpend struct {
	Context *middleware.Context
	Handler PostUsersIDSpendHandler
}

func (o *PostUsersIDSpend) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostUsersIDSpendParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
