// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Space-Market
//
//  API for transactions
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /v3
//  Version: 3.0.0
//  License: MIT https://opensource.org/licenses/MIT
//
//  Consumes:
//    - application/json
//    - multipart/form-data
//
//  Produces:
//    - image/gif
//    - image/jpeg
//    - image/png
//    - application/json
//
// swagger:meta
package restapi
