// Code generated by go-swagger; DO NOT EDIT.

package barcodes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteBarcodesIDHandlerFunc turns a function with the right signature into a delete barcodes ID handler
type DeleteBarcodesIDHandlerFunc func(DeleteBarcodesIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteBarcodesIDHandlerFunc) Handle(params DeleteBarcodesIDParams) middleware.Responder {
	return fn(params)
}

// DeleteBarcodesIDHandler interface for that can handle valid delete barcodes ID params
type DeleteBarcodesIDHandler interface {
	Handle(DeleteBarcodesIDParams) middleware.Responder
}

// NewDeleteBarcodesID creates a new http.Handler for the delete barcodes ID operation
func NewDeleteBarcodesID(ctx *middleware.Context, handler DeleteBarcodesIDHandler) *DeleteBarcodesID {
	return &DeleteBarcodesID{Context: ctx, Handler: handler}
}

/*DeleteBarcodesID swagger:route DELETE /barcodes/{id}/ barcodes deleteBarcodesId

delete the barcode

*/
type DeleteBarcodesID struct {
	Context *middleware.Context
	Handler DeleteBarcodesIDHandler
}

func (o *DeleteBarcodesID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteBarcodesIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
