// Code generated by go-swagger; DO NOT EDIT.

package barcodes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteBarcodesIDNoContentCode is the HTTP code returned for type DeleteBarcodesIDNoContent
const DeleteBarcodesIDNoContentCode int = 204

/*DeleteBarcodesIDNoContent barcode deleted

swagger:response deleteBarcodesIdNoContent
*/
type DeleteBarcodesIDNoContent struct {
}

// NewDeleteBarcodesIDNoContent creates DeleteBarcodesIDNoContent with default headers values
func NewDeleteBarcodesIDNoContent() *DeleteBarcodesIDNoContent {

	return &DeleteBarcodesIDNoContent{}
}

// WriteResponse to the client
func (o *DeleteBarcodesIDNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// DeleteBarcodesIDNotFoundCode is the HTTP code returned for type DeleteBarcodesIDNotFound
const DeleteBarcodesIDNotFoundCode int = 404

/*DeleteBarcodesIDNotFound barcode not existent

swagger:response deleteBarcodesIdNotFound
*/
type DeleteBarcodesIDNotFound struct {
}

// NewDeleteBarcodesIDNotFound creates DeleteBarcodesIDNotFound with default headers values
func NewDeleteBarcodesIDNotFound() *DeleteBarcodesIDNotFound {

	return &DeleteBarcodesIDNotFound{}
}

// WriteResponse to the client
func (o *DeleteBarcodesIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// DeleteBarcodesIDInternalServerErrorCode is the HTTP code returned for type DeleteBarcodesIDInternalServerError
const DeleteBarcodesIDInternalServerErrorCode int = 500

/*DeleteBarcodesIDInternalServerError server error

swagger:response deleteBarcodesIdInternalServerError
*/
type DeleteBarcodesIDInternalServerError struct {
}

// NewDeleteBarcodesIDInternalServerError creates DeleteBarcodesIDInternalServerError with default headers values
func NewDeleteBarcodesIDInternalServerError() *DeleteBarcodesIDInternalServerError {

	return &DeleteBarcodesIDInternalServerError{}
}

// WriteResponse to the client
func (o *DeleteBarcodesIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
