// Code generated by go-swagger; DO NOT EDIT.

package barcodes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/cccfr/gomete/models"
)

// GetBarcodesIDOKCode is the HTTP code returned for type GetBarcodesIDOK
const GetBarcodesIDOKCode int = 200

/*GetBarcodesIDOK details of barcode

swagger:response getBarcodesIdOK
*/
type GetBarcodesIDOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Barcode `json:"body,omitempty"`
}

// NewGetBarcodesIDOK creates GetBarcodesIDOK with default headers values
func NewGetBarcodesIDOK() *GetBarcodesIDOK {

	return &GetBarcodesIDOK{}
}

// WithPayload adds the payload to the get barcodes Id o k response
func (o *GetBarcodesIDOK) WithPayload(payload []*models.Barcode) *GetBarcodesIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get barcodes Id o k response
func (o *GetBarcodesIDOK) SetPayload(payload []*models.Barcode) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBarcodesIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Barcode, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetBarcodesIDNotFoundCode is the HTTP code returned for type GetBarcodesIDNotFound
const GetBarcodesIDNotFoundCode int = 404

/*GetBarcodesIDNotFound barcode not existent

swagger:response getBarcodesIdNotFound
*/
type GetBarcodesIDNotFound struct {
}

// NewGetBarcodesIDNotFound creates GetBarcodesIDNotFound with default headers values
func NewGetBarcodesIDNotFound() *GetBarcodesIDNotFound {

	return &GetBarcodesIDNotFound{}
}

// WriteResponse to the client
func (o *GetBarcodesIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// GetBarcodesIDInternalServerErrorCode is the HTTP code returned for type GetBarcodesIDInternalServerError
const GetBarcodesIDInternalServerErrorCode int = 500

/*GetBarcodesIDInternalServerError server error

swagger:response getBarcodesIdInternalServerError
*/
type GetBarcodesIDInternalServerError struct {
}

// NewGetBarcodesIDInternalServerError creates GetBarcodesIDInternalServerError with default headers values
func NewGetBarcodesIDInternalServerError() *GetBarcodesIDInternalServerError {

	return &GetBarcodesIDInternalServerError{}
}

// WriteResponse to the client
func (o *GetBarcodesIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
