// Code generated by go-swagger; DO NOT EDIT.

package barcodes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/cccfr/gomete/models"
)

// PatchBarcodesIDOKCode is the HTTP code returned for type PatchBarcodesIDOK
const PatchBarcodesIDOKCode int = 200

/*PatchBarcodesIDOK barcode updated

swagger:response patchBarcodesIdOK
*/
type PatchBarcodesIDOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Barcode `json:"body,omitempty"`
}

// NewPatchBarcodesIDOK creates PatchBarcodesIDOK with default headers values
func NewPatchBarcodesIDOK() *PatchBarcodesIDOK {

	return &PatchBarcodesIDOK{}
}

// WithPayload adds the payload to the patch barcodes Id o k response
func (o *PatchBarcodesIDOK) WithPayload(payload []*models.Barcode) *PatchBarcodesIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch barcodes Id o k response
func (o *PatchBarcodesIDOK) SetPayload(payload []*models.Barcode) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchBarcodesIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Barcode, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// PatchBarcodesIDBadRequestCode is the HTTP code returned for type PatchBarcodesIDBadRequest
const PatchBarcodesIDBadRequestCode int = 400

/*PatchBarcodesIDBadRequest bad request

swagger:response patchBarcodesIdBadRequest
*/
type PatchBarcodesIDBadRequest struct {
}

// NewPatchBarcodesIDBadRequest creates PatchBarcodesIDBadRequest with default headers values
func NewPatchBarcodesIDBadRequest() *PatchBarcodesIDBadRequest {

	return &PatchBarcodesIDBadRequest{}
}

// WriteResponse to the client
func (o *PatchBarcodesIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// PatchBarcodesIDNotFoundCode is the HTTP code returned for type PatchBarcodesIDNotFound
const PatchBarcodesIDNotFoundCode int = 404

/*PatchBarcodesIDNotFound barcode not existent

swagger:response patchBarcodesIdNotFound
*/
type PatchBarcodesIDNotFound struct {
}

// NewPatchBarcodesIDNotFound creates PatchBarcodesIDNotFound with default headers values
func NewPatchBarcodesIDNotFound() *PatchBarcodesIDNotFound {

	return &PatchBarcodesIDNotFound{}
}

// WriteResponse to the client
func (o *PatchBarcodesIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// PatchBarcodesIDInternalServerErrorCode is the HTTP code returned for type PatchBarcodesIDInternalServerError
const PatchBarcodesIDInternalServerErrorCode int = 500

/*PatchBarcodesIDInternalServerError server error

swagger:response patchBarcodesIdInternalServerError
*/
type PatchBarcodesIDInternalServerError struct {
}

// NewPatchBarcodesIDInternalServerError creates PatchBarcodesIDInternalServerError with default headers values
func NewPatchBarcodesIDInternalServerError() *PatchBarcodesIDInternalServerError {

	return &PatchBarcodesIDInternalServerError{}
}

// WriteResponse to the client
func (o *PatchBarcodesIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
