// Code generated by go-swagger; DO NOT EDIT.

package barcodes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/cccfr/gomete/models"
)

// PostBarcodesOKCode is the HTTP code returned for type PostBarcodesOK
const PostBarcodesOKCode int = 200

/*PostBarcodesOK created barcode

swagger:response postBarcodesOK
*/
type PostBarcodesOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Barcode `json:"body,omitempty"`
}

// NewPostBarcodesOK creates PostBarcodesOK with default headers values
func NewPostBarcodesOK() *PostBarcodesOK {

	return &PostBarcodesOK{}
}

// WithPayload adds the payload to the post barcodes o k response
func (o *PostBarcodesOK) WithPayload(payload []*models.Barcode) *PostBarcodesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post barcodes o k response
func (o *PostBarcodesOK) SetPayload(payload []*models.Barcode) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostBarcodesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Barcode, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// PostBarcodesBadRequestCode is the HTTP code returned for type PostBarcodesBadRequest
const PostBarcodesBadRequestCode int = 400

/*PostBarcodesBadRequest bad request

swagger:response postBarcodesBadRequest
*/
type PostBarcodesBadRequest struct {
}

// NewPostBarcodesBadRequest creates PostBarcodesBadRequest with default headers values
func NewPostBarcodesBadRequest() *PostBarcodesBadRequest {

	return &PostBarcodesBadRequest{}
}

// WriteResponse to the client
func (o *PostBarcodesBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// PostBarcodesConflictCode is the HTTP code returned for type PostBarcodesConflict
const PostBarcodesConflictCode int = 409

/*PostBarcodesConflict a barcode with this name already exists

swagger:response postBarcodesConflict
*/
type PostBarcodesConflict struct {
}

// NewPostBarcodesConflict creates PostBarcodesConflict with default headers values
func NewPostBarcodesConflict() *PostBarcodesConflict {

	return &PostBarcodesConflict{}
}

// WriteResponse to the client
func (o *PostBarcodesConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(409)
}

// PostBarcodesInternalServerErrorCode is the HTTP code returned for type PostBarcodesInternalServerError
const PostBarcodesInternalServerErrorCode int = 500

/*PostBarcodesInternalServerError server error

swagger:response postBarcodesInternalServerError
*/
type PostBarcodesInternalServerError struct {
}

// NewPostBarcodesInternalServerError creates PostBarcodesInternalServerError with default headers values
func NewPostBarcodesInternalServerError() *PostBarcodesInternalServerError {

	return &PostBarcodesInternalServerError{}
}

// WriteResponse to the client
func (o *PostBarcodesInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
