// Code generated by go-swagger; DO NOT EDIT.

package barcodes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
)

// NewPostBarcodesParams creates a new PostBarcodesParams object
// no default values defined in spec.
func NewPostBarcodesParams() PostBarcodesParams {

	return PostBarcodesParams{}
}

// PostBarcodesParams contains all the bound params for the post barcodes operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostBarcodes
type PostBarcodesParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: body
	*/
	Barcode PostBarcodesBody
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostBarcodesParams() beforehand.
func (o *PostBarcodesParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body PostBarcodesBody
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("barcode", "body", ""))
			} else {
				res = append(res, errors.NewParseError("barcode", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Barcode = body
			}
		}
	} else {
		res = append(res, errors.Required("barcode", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
