// Code generated by go-swagger; DO NOT EDIT.

package image

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetImagesIDImgOKCode is the HTTP code returned for type GetImagesIDImgOK
const GetImagesIDImgOKCode int = 200

/*GetImagesIDImgOK image data blob

swagger:response getImagesIdImgOK
*/
type GetImagesIDImgOK struct {
}

// NewGetImagesIDImgOK creates GetImagesIDImgOK with default headers values
func NewGetImagesIDImgOK() *GetImagesIDImgOK {

	return &GetImagesIDImgOK{}
}

// WriteResponse to the client
func (o *GetImagesIDImgOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// GetImagesIDImgNotFoundCode is the HTTP code returned for type GetImagesIDImgNotFound
const GetImagesIDImgNotFoundCode int = 404

/*GetImagesIDImgNotFound id not existent

swagger:response getImagesIdImgNotFound
*/
type GetImagesIDImgNotFound struct {
}

// NewGetImagesIDImgNotFound creates GetImagesIDImgNotFound with default headers values
func NewGetImagesIDImgNotFound() *GetImagesIDImgNotFound {

	return &GetImagesIDImgNotFound{}
}

// WriteResponse to the client
func (o *GetImagesIDImgNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// GetImagesIDImgInternalServerErrorCode is the HTTP code returned for type GetImagesIDImgInternalServerError
const GetImagesIDImgInternalServerErrorCode int = 500

/*GetImagesIDImgInternalServerError server error i.e.

swagger:response getImagesIdImgInternalServerError
*/
type GetImagesIDImgInternalServerError struct {
}

// NewGetImagesIDImgInternalServerError creates GetImagesIDImgInternalServerError with default headers values
func NewGetImagesIDImgInternalServerError() *GetImagesIDImgInternalServerError {

	return &GetImagesIDImgInternalServerError{}
}

// WriteResponse to the client
func (o *GetImagesIDImgInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
