// Code generated by go-swagger; DO NOT EDIT.

package image

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetImagesIDImgHandlerFunc turns a function with the right signature into a get images ID img handler
type GetImagesIDImgHandlerFunc func(GetImagesIDImgParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetImagesIDImgHandlerFunc) Handle(params GetImagesIDImgParams) middleware.Responder {
	return fn(params)
}

// GetImagesIDImgHandler interface for that can handle valid get images ID img params
type GetImagesIDImgHandler interface {
	Handle(GetImagesIDImgParams) middleware.Responder
}

// NewGetImagesIDImg creates a new http.Handler for the get images ID img operation
func NewGetImagesIDImg(ctx *middleware.Context, handler GetImagesIDImgHandler) *GetImagesIDImg {
	return &GetImagesIDImg{Context: ctx, Handler: handler}
}

/*GetImagesIDImg swagger:route GET /images/{id}/img image getImagesIdImg

image data

image data

*/
type GetImagesIDImg struct {
	Context *middleware.Context
	Handler GetImagesIDImgHandler
}

func (o *GetImagesIDImg) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetImagesIDImgParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
