// Code generated by go-swagger; DO NOT EDIT.

package image

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetImagesNoContentCode is the HTTP code returned for type GetImagesNoContent
const GetImagesNoContentCode int = 204

/*GetImagesNoContent The serve is capable of handling images

swagger:response getImagesNoContent
*/
type GetImagesNoContent struct {
}

// NewGetImagesNoContent creates GetImagesNoContent with default headers values
func NewGetImagesNoContent() *GetImagesNoContent {

	return &GetImagesNoContent{}
}

// WriteResponse to the client
func (o *GetImagesNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// GetImagesNotImplementedCode is the HTTP code returned for type GetImagesNotImplemented
const GetImagesNotImplementedCode int = 501

/*GetImagesNotImplemented not implemented

swagger:response getImagesNotImplemented
*/
type GetImagesNotImplemented struct {
}

// NewGetImagesNotImplemented creates GetImagesNotImplemented with default headers values
func NewGetImagesNotImplemented() *GetImagesNotImplemented {

	return &GetImagesNotImplemented{}
}

// WriteResponse to the client
func (o *GetImagesNotImplemented) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(501)
}
