// Code generated by go-swagger; DO NOT EDIT.

package image

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetImagesIDHandlerFunc turns a function with the right signature into a get images ID handler
type GetImagesIDHandlerFunc func(GetImagesIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetImagesIDHandlerFunc) Handle(params GetImagesIDParams) middleware.Responder {
	return fn(params)
}

// GetImagesIDHandler interface for that can handle valid get images ID params
type GetImagesIDHandler interface {
	Handle(GetImagesIDParams) middleware.Responder
}

// NewGetImagesID creates a new http.Handler for the get images ID operation
func NewGetImagesID(ctx *middleware.Context, handler GetImagesIDHandler) *GetImagesID {
	return &GetImagesID{Context: ctx, Handler: handler}
}

/*GetImagesID swagger:route GET /images/{id} image getImagesId

image metadata

*/
type GetImagesID struct {
	Context *middleware.Context
	Handler GetImagesIDHandler
}

func (o *GetImagesID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetImagesIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
