// Code generated by go-swagger; DO NOT EDIT.

package image

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/cccfr/gomete/models"
)

// PostImagesOKCode is the HTTP code returned for type PostImagesOK
const PostImagesOKCode int = 200

/*PostImagesOK OK

swagger:response postImagesOK
*/
type PostImagesOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Image `json:"body,omitempty"`
}

// NewPostImagesOK creates PostImagesOK with default headers values
func NewPostImagesOK() *PostImagesOK {

	return &PostImagesOK{}
}

// WithPayload adds the payload to the post images o k response
func (o *PostImagesOK) WithPayload(payload []*models.Image) *PostImagesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post images o k response
func (o *PostImagesOK) SetPayload(payload []*models.Image) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostImagesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Image, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// PostImagesRequestEntityTooLargeCode is the HTTP code returned for type PostImagesRequestEntityTooLarge
const PostImagesRequestEntityTooLargeCode int = 413

/*PostImagesRequestEntityTooLarge uploaded file to large

swagger:response postImagesRequestEntityTooLarge
*/
type PostImagesRequestEntityTooLarge struct {
}

// NewPostImagesRequestEntityTooLarge creates PostImagesRequestEntityTooLarge with default headers values
func NewPostImagesRequestEntityTooLarge() *PostImagesRequestEntityTooLarge {

	return &PostImagesRequestEntityTooLarge{}
}

// WriteResponse to the client
func (o *PostImagesRequestEntityTooLarge) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(413)
}

// PostImagesUnsupportedMediaTypeCode is the HTTP code returned for type PostImagesUnsupportedMediaType
const PostImagesUnsupportedMediaTypeCode int = 415

/*PostImagesUnsupportedMediaType unsupported media type

swagger:response postImagesUnsupportedMediaType
*/
type PostImagesUnsupportedMediaType struct {
}

// NewPostImagesUnsupportedMediaType creates PostImagesUnsupportedMediaType with default headers values
func NewPostImagesUnsupportedMediaType() *PostImagesUnsupportedMediaType {

	return &PostImagesUnsupportedMediaType{}
}

// WriteResponse to the client
func (o *PostImagesUnsupportedMediaType) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(415)
}

// PostImagesInternalServerErrorCode is the HTTP code returned for type PostImagesInternalServerError
const PostImagesInternalServerErrorCode int = 500

/*PostImagesInternalServerError server error

swagger:response postImagesInternalServerError
*/
type PostImagesInternalServerError struct {
}

// NewPostImagesInternalServerError creates PostImagesInternalServerError with default headers values
func NewPostImagesInternalServerError() *PostImagesInternalServerError {

	return &PostImagesInternalServerError{}
}

// WriteResponse to the client
func (o *PostImagesInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
