// Code generated by go-swagger; DO NOT EDIT.

package denominations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteDenominationsIDNoContentCode is the HTTP code returned for type DeleteDenominationsIDNoContent
const DeleteDenominationsIDNoContentCode int = 204

/*DeleteDenominationsIDNoContent denomination deleted

swagger:response deleteDenominationsIdNoContent
*/
type DeleteDenominationsIDNoContent struct {
}

// NewDeleteDenominationsIDNoContent creates DeleteDenominationsIDNoContent with default headers values
func NewDeleteDenominationsIDNoContent() *DeleteDenominationsIDNoContent {

	return &DeleteDenominationsIDNoContent{}
}

// WriteResponse to the client
func (o *DeleteDenominationsIDNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// DeleteDenominationsIDNotFoundCode is the HTTP code returned for type DeleteDenominationsIDNotFound
const DeleteDenominationsIDNotFoundCode int = 404

/*DeleteDenominationsIDNotFound id not existent

swagger:response deleteDenominationsIdNotFound
*/
type DeleteDenominationsIDNotFound struct {
}

// NewDeleteDenominationsIDNotFound creates DeleteDenominationsIDNotFound with default headers values
func NewDeleteDenominationsIDNotFound() *DeleteDenominationsIDNotFound {

	return &DeleteDenominationsIDNotFound{}
}

// WriteResponse to the client
func (o *DeleteDenominationsIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// DeleteDenominationsIDInternalServerErrorCode is the HTTP code returned for type DeleteDenominationsIDInternalServerError
const DeleteDenominationsIDInternalServerErrorCode int = 500

/*DeleteDenominationsIDInternalServerError server error

swagger:response deleteDenominationsIdInternalServerError
*/
type DeleteDenominationsIDInternalServerError struct {
}

// NewDeleteDenominationsIDInternalServerError creates DeleteDenominationsIDInternalServerError with default headers values
func NewDeleteDenominationsIDInternalServerError() *DeleteDenominationsIDInternalServerError {

	return &DeleteDenominationsIDInternalServerError{}
}

// WriteResponse to the client
func (o *DeleteDenominationsIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
