// Code generated by go-swagger; DO NOT EDIT.

package denominations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetDenominationsHandlerFunc turns a function with the right signature into a get denominations handler
type GetDenominationsHandlerFunc func(GetDenominationsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetDenominationsHandlerFunc) Handle(params GetDenominationsParams) middleware.Responder {
	return fn(params)
}

// GetDenominationsHandler interface for that can handle valid get denominations params
type GetDenominationsHandler interface {
	Handle(GetDenominationsParams) middleware.Responder
}

// NewGetDenominations creates a new http.Handler for the get denominations operation
func NewGetDenominations(ctx *middleware.Context, handler GetDenominationsHandler) *GetDenominations {
	return &GetDenominations{Context: ctx, Handler: handler}
}

/*GetDenominations swagger:route GET /denominations/ denominations getDenominations

get a list of all configured denominations

*/
type GetDenominations struct {
	Context *middleware.Context
	Handler GetDenominationsHandler
}

func (o *GetDenominations) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetDenominationsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
