// Code generated by go-swagger; DO NOT EDIT.

package denominations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/cccfr/gomete/models"
)

// GetDenominationsIDOKCode is the HTTP code returned for type GetDenominationsIDOK
const GetDenominationsIDOKCode int = 200

/*GetDenominationsIDOK details of denomination

swagger:response getDenominationsIdOK
*/
type GetDenominationsIDOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Denomination `json:"body,omitempty"`
}

// NewGetDenominationsIDOK creates GetDenominationsIDOK with default headers values
func NewGetDenominationsIDOK() *GetDenominationsIDOK {

	return &GetDenominationsIDOK{}
}

// WithPayload adds the payload to the get denominations Id o k response
func (o *GetDenominationsIDOK) WithPayload(payload []*models.Denomination) *GetDenominationsIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get denominations Id o k response
func (o *GetDenominationsIDOK) SetPayload(payload []*models.Denomination) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDenominationsIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Denomination, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetDenominationsIDBadRequestCode is the HTTP code returned for type GetDenominationsIDBadRequest
const GetDenominationsIDBadRequestCode int = 400

/*GetDenominationsIDBadRequest bad request

swagger:response getDenominationsIdBadRequest
*/
type GetDenominationsIDBadRequest struct {
}

// NewGetDenominationsIDBadRequest creates GetDenominationsIDBadRequest with default headers values
func NewGetDenominationsIDBadRequest() *GetDenominationsIDBadRequest {

	return &GetDenominationsIDBadRequest{}
}

// WriteResponse to the client
func (o *GetDenominationsIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// GetDenominationsIDNotFoundCode is the HTTP code returned for type GetDenominationsIDNotFound
const GetDenominationsIDNotFoundCode int = 404

/*GetDenominationsIDNotFound id not existent

swagger:response getDenominationsIdNotFound
*/
type GetDenominationsIDNotFound struct {
}

// NewGetDenominationsIDNotFound creates GetDenominationsIDNotFound with default headers values
func NewGetDenominationsIDNotFound() *GetDenominationsIDNotFound {

	return &GetDenominationsIDNotFound{}
}

// WriteResponse to the client
func (o *GetDenominationsIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// GetDenominationsIDInternalServerErrorCode is the HTTP code returned for type GetDenominationsIDInternalServerError
const GetDenominationsIDInternalServerErrorCode int = 500

/*GetDenominationsIDInternalServerError server error

swagger:response getDenominationsIdInternalServerError
*/
type GetDenominationsIDInternalServerError struct {
}

// NewGetDenominationsIDInternalServerError creates GetDenominationsIDInternalServerError with default headers values
func NewGetDenominationsIDInternalServerError() *GetDenominationsIDInternalServerError {

	return &GetDenominationsIDInternalServerError{}
}

// WriteResponse to the client
func (o *GetDenominationsIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
