// Code generated by go-swagger; DO NOT EDIT.

package denominations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/cccfr/gomete/models"
)

// GetDenominationsOKCode is the HTTP code returned for type GetDenominationsOK
const GetDenominationsOKCode int = 200

/*GetDenominationsOK list of denominations

swagger:response getDenominationsOK
*/
type GetDenominationsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Denomination `json:"body,omitempty"`
}

// NewGetDenominationsOK creates GetDenominationsOK with default headers values
func NewGetDenominationsOK() *GetDenominationsOK {

	return &GetDenominationsOK{}
}

// WithPayload adds the payload to the get denominations o k response
func (o *GetDenominationsOK) WithPayload(payload []*models.Denomination) *GetDenominationsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get denominations o k response
func (o *GetDenominationsOK) SetPayload(payload []*models.Denomination) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDenominationsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Denomination, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetDenominationsBadRequestCode is the HTTP code returned for type GetDenominationsBadRequest
const GetDenominationsBadRequestCode int = 400

/*GetDenominationsBadRequest bad request

swagger:response getDenominationsBadRequest
*/
type GetDenominationsBadRequest struct {
}

// NewGetDenominationsBadRequest creates GetDenominationsBadRequest with default headers values
func NewGetDenominationsBadRequest() *GetDenominationsBadRequest {

	return &GetDenominationsBadRequest{}
}

// WriteResponse to the client
func (o *GetDenominationsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// GetDenominationsConflictCode is the HTTP code returned for type GetDenominationsConflict
const GetDenominationsConflictCode int = 409

/*GetDenominationsConflict a denomination with this value already exists

swagger:response getDenominationsConflict
*/
type GetDenominationsConflict struct {
}

// NewGetDenominationsConflict creates GetDenominationsConflict with default headers values
func NewGetDenominationsConflict() *GetDenominationsConflict {

	return &GetDenominationsConflict{}
}

// WriteResponse to the client
func (o *GetDenominationsConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(409)
}

// GetDenominationsInternalServerErrorCode is the HTTP code returned for type GetDenominationsInternalServerError
const GetDenominationsInternalServerErrorCode int = 500

/*GetDenominationsInternalServerError server error

swagger:response getDenominationsInternalServerError
*/
type GetDenominationsInternalServerError struct {
}

// NewGetDenominationsInternalServerError creates GetDenominationsInternalServerError with default headers values
func NewGetDenominationsInternalServerError() *GetDenominationsInternalServerError {

	return &GetDenominationsInternalServerError{}
}

// WriteResponse to the client
func (o *GetDenominationsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
