// Code generated by go-swagger; DO NOT EDIT.

package denominations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PostDenominationsHandlerFunc turns a function with the right signature into a post denominations handler
type PostDenominationsHandlerFunc func(PostDenominationsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostDenominationsHandlerFunc) Handle(params PostDenominationsParams) middleware.Responder {
	return fn(params)
}

// PostDenominationsHandler interface for that can handle valid post denominations params
type PostDenominationsHandler interface {
	Handle(PostDenominationsParams) middleware.Responder
}

// NewPostDenominations creates a new http.Handler for the post denominations operation
func NewPostDenominations(ctx *middleware.Context, handler PostDenominationsHandler) *PostDenominations {
	return &PostDenominations{Context: ctx, Handler: handler}
}

/*PostDenominations swagger:route POST /denominations/ denominations postDenominations

create a new denomination

*/
type PostDenominations struct {
	Context *middleware.Context
	Handler PostDenominationsHandler
}

func (o *PostDenominations) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostDenominationsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// PostDenominationsBody post denominations body
//
// swagger:model PostDenominationsBody
type PostDenominationsBody struct {

	// amount
	Amount int64 `json:"amount,omitempty"`

	// id of linked image
	Image int64 `json:"image,omitempty"`
}

// Validate validates this post denominations body
func (o *PostDenominationsBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostDenominationsBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostDenominationsBody) UnmarshalBinary(b []byte) error {
	var res PostDenominationsBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
