// Code generated by go-swagger; DO NOT EDIT.

package denominations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/cccfr/gomete/models"
)

// PostDenominationsOKCode is the HTTP code returned for type PostDenominationsOK
const PostDenominationsOKCode int = 200

/*PostDenominationsOK created denomination

swagger:response postDenominationsOK
*/
type PostDenominationsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Denomination `json:"body,omitempty"`
}

// NewPostDenominationsOK creates PostDenominationsOK with default headers values
func NewPostDenominationsOK() *PostDenominationsOK {

	return &PostDenominationsOK{}
}

// WithPayload adds the payload to the post denominations o k response
func (o *PostDenominationsOK) WithPayload(payload []*models.Denomination) *PostDenominationsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post denominations o k response
func (o *PostDenominationsOK) SetPayload(payload []*models.Denomination) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostDenominationsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Denomination, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// PostDenominationsBadRequestCode is the HTTP code returned for type PostDenominationsBadRequest
const PostDenominationsBadRequestCode int = 400

/*PostDenominationsBadRequest bad request

swagger:response postDenominationsBadRequest
*/
type PostDenominationsBadRequest struct {
}

// NewPostDenominationsBadRequest creates PostDenominationsBadRequest with default headers values
func NewPostDenominationsBadRequest() *PostDenominationsBadRequest {

	return &PostDenominationsBadRequest{}
}

// WriteResponse to the client
func (o *PostDenominationsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// PostDenominationsConflictCode is the HTTP code returned for type PostDenominationsConflict
const PostDenominationsConflictCode int = 409

/*PostDenominationsConflict a denominations with this amount already exists

swagger:response postDenominationsConflict
*/
type PostDenominationsConflict struct {
}

// NewPostDenominationsConflict creates PostDenominationsConflict with default headers values
func NewPostDenominationsConflict() *PostDenominationsConflict {

	return &PostDenominationsConflict{}
}

// WriteResponse to the client
func (o *PostDenominationsConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(409)
}

// PostDenominationsInternalServerErrorCode is the HTTP code returned for type PostDenominationsInternalServerError
const PostDenominationsInternalServerErrorCode int = 500

/*PostDenominationsInternalServerError server error

swagger:response postDenominationsInternalServerError
*/
type PostDenominationsInternalServerError struct {
}

// NewPostDenominationsInternalServerError creates PostDenominationsInternalServerError with default headers values
func NewPostDenominationsInternalServerError() *PostDenominationsInternalServerError {

	return &PostDenominationsInternalServerError{}
}

// WriteResponse to the client
func (o *PostDenominationsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
