// Code generated by go-swagger; DO NOT EDIT.

package audits

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// NewGetAuditsParams creates a new GetAuditsParams object
// no default values defined in spec.
func NewGetAuditsParams() GetAuditsParams {

	return GetAuditsParams{}
}

// GetAuditsParams contains all the bound params for the get audits operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetAudits
type GetAuditsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*end date in ISO8601 format
	  In: query
	*/
	End *strfmt.Date
	/*start date in ISO8601 format
	  Required: true
	  In: query
	*/
	Start strfmt.Date
	/*
	  In: query
	*/
	User *int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetAuditsParams() beforehand.
func (o *GetAuditsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qEnd, qhkEnd, _ := qs.GetOK("end")
	if err := o.bindEnd(qEnd, qhkEnd, route.Formats); err != nil {
		res = append(res, err)
	}

	qStart, qhkStart, _ := qs.GetOK("start")
	if err := o.bindStart(qStart, qhkStart, route.Formats); err != nil {
		res = append(res, err)
	}

	qUser, qhkUser, _ := qs.GetOK("user")
	if err := o.bindUser(qUser, qhkUser, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindEnd binds and validates parameter End from query.
func (o *GetAuditsParams) bindEnd(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	// Format: date
	value, err := formats.Parse("date", raw)
	if err != nil {
		return errors.InvalidType("end", "query", "strfmt.Date", raw)
	}
	o.End = (value.(*strfmt.Date))

	if err := o.validateEnd(formats); err != nil {
		return err
	}

	return nil
}

// validateEnd carries on validations for parameter End
func (o *GetAuditsParams) validateEnd(formats strfmt.Registry) error {

	if err := validate.FormatOf("end", "query", "date", o.End.String(), formats); err != nil {
		return err
	}
	return nil
}

// bindStart binds and validates parameter Start from query.
func (o *GetAuditsParams) bindStart(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("start", "query", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false
	if err := validate.RequiredString("start", "query", raw); err != nil {
		return err
	}

	// Format: date
	value, err := formats.Parse("date", raw)
	if err != nil {
		return errors.InvalidType("start", "query", "strfmt.Date", raw)
	}
	o.Start = *(value.(*strfmt.Date))

	if err := o.validateStart(formats); err != nil {
		return err
	}

	return nil
}

// validateStart carries on validations for parameter Start
func (o *GetAuditsParams) validateStart(formats strfmt.Registry) error {

	if err := validate.FormatOf("start", "query", "date", o.Start.String(), formats); err != nil {
		return err
	}
	return nil
}

// bindUser binds and validates parameter User from query.
func (o *GetAuditsParams) bindUser(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("user", "query", "int64", raw)
	}
	o.User = &value

	return nil
}
