// Code generated by go-swagger; DO NOT EDIT.

package audits

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetAuditsOKCode is the HTTP code returned for type GetAuditsOK
const GetAuditsOKCode int = 200

/*GetAuditsOK audits

swagger:response getAuditsOK
*/
type GetAuditsOK struct {

	/*
	  In: Body
	*/
	Payload *GetAuditsOKBody `json:"body,omitempty"`
}

// NewGetAuditsOK creates GetAuditsOK with default headers values
func NewGetAuditsOK() *GetAuditsOK {

	return &GetAuditsOK{}
}

// WithPayload adds the payload to the get audits o k response
func (o *GetAuditsOK) WithPayload(payload *GetAuditsOKBody) *GetAuditsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get audits o k response
func (o *GetAuditsOK) SetPayload(payload *GetAuditsOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAuditsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAuditsUnauthorizedCode is the HTTP code returned for type GetAuditsUnauthorized
const GetAuditsUnauthorizedCode int = 401

/*GetAuditsUnauthorized Audits deactivated by user

swagger:response getAuditsUnauthorized
*/
type GetAuditsUnauthorized struct {
}

// NewGetAuditsUnauthorized creates GetAuditsUnauthorized with default headers values
func NewGetAuditsUnauthorized() *GetAuditsUnauthorized {

	return &GetAuditsUnauthorized{}
}

// WriteResponse to the client
func (o *GetAuditsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// GetAuditsInternalServerErrorCode is the HTTP code returned for type GetAuditsInternalServerError
const GetAuditsInternalServerErrorCode int = 500

/*GetAuditsInternalServerError Server error

swagger:response getAuditsInternalServerError
*/
type GetAuditsInternalServerError struct {
}

// NewGetAuditsInternalServerError creates GetAuditsInternalServerError with default headers values
func NewGetAuditsInternalServerError() *GetAuditsInternalServerError {

	return &GetAuditsInternalServerError{}
}

// WriteResponse to the client
func (o *GetAuditsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
